### ISSUE TITLE
Doesn't seem to work on my setup, is it possible to add something to the controls menu to change the default hotkeys?

### ISSUE THREAD

**Issue by EmoCthulhu** [esheyw/settings-hotkeys#1]
It's a great idea, so I grabbed it right away. However, none of the default hotkeys work for me, and as a request, it would be great if you could change them from the default. Not sure if it could be a module conflict or not, but since Alt causes every token to light up on my setup, I'm thinking possitbly Illandril's Token Tooltips causes it, and I'll be checking that in a second. 

I take it back, I thought I had some other functions that used Alt, but it's actually default Foundry that uses both Alt's to highlight objects. As well default Foundry itself uses Alt-1 to Alt-5 to switch hotbars, and while it lights up all objects just like when I try to use your module, the hotbars do change, while Alt-Z, Alt-X, Alt-Shift-Z do nothing. 

I've tried disabling or changing the hotkey settings for all modules that had Alt in their value, and still got nothing. Disabled AltLeft as a way to highlight all objects in the Core Controls, and AltLeft-Z, AltLeft-X, AltLeft-Shift-Z still do nothing. Disabled AltRight in Core Controls, and still nothing happened with AltRight-Z, AltRight-X, AltLeft-Shift-Z. 

Windows 11, Foundry V11 build 315, also on Forge - happens in native Foundry and on Forge. To replicate, install the module and activate it.

**Comment by esheyw** [comment]
So this module is mostly code I copied from a personal module, and I didn't catch that I'd renamed the constant defining the module ID. So the keybinds were being registered for the module ID... `undefined` 🤦‍♂️. No idea how that didn't throw an error, but it was hiding them from the config settings window. They were always intended to be configurable. Should be fixed in 1.0.1.
